server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 390c240c-000a-4d84-8d19-298cc77f86d3
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
          # 唯一标识
        - id: user_route
          # 转发的路径规则，可以是http://xxx，也可以是nocos上的服务注册名lb://{xxxx}
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**
#            # 自定义谓词工厂，开始时间和结束时间
#            - TimeBetween=上午12:10,下午4:00
#          filters:
#            # 在请求转发时在header中加入 key=X-Request-Foo, value=Bar
#            - AddRequestHeader=X-Request-Foo, Bar
#            # 自定义过滤器，打印日志 key=a, value=b
#            - PreLog=a, b
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      # 抽样率，默认是0.1=10%
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug